/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 21491ef208b24379ecd0d23916dc9533)
interface __BaseEnv_Env {
	DB: D1Database;
	ROOM: DurableObjectNamespace<import("./worker/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
